document.addEventListener("DOMContentLoaded", () => {
  // Check if user is logged in, if not redirect to login page
  if (!localStorage.getItem("token")) {
    window.location.href = "index.html";
    return;
  }

  // Show admin navigation if user is admin
  if (localStorage.getItem("isAdmin") === "true") {
    document.getElementById("admin-nav").style.display = "block";
  }

  // Setup logout button
  document.getElementById("logout-btn").addEventListener("click", () => {
    localStorage.removeItem("token");
    localStorage.removeItem("userId");
    localStorage.removeItem("isAdmin");
    window.location.href = "index.html";
  });

  // Setup view toggle buttons
  const gridViewBtn = document.querySelector("#grid-view-btn");
  const listViewBtn = document.querySelector("#list-view-btn");

  if (gridViewBtn && listViewBtn) {
    // Remove any existing event listeners
    const newGridBtn = gridViewBtn.cloneNode(true);
    const newListBtn = listViewBtn.cloneNode(true);

    gridViewBtn.parentNode.replaceChild(newGridBtn, gridViewBtn);
    listViewBtn.parentNode.replaceChild(newListBtn, listViewBtn);

    // Add fresh event listeners
    newGridBtn.addEventListener("click", () => {
      console.log("Grid view button clicked");
      setActiveView("grid");
    });

    newListBtn.addEventListener("click", () => {
      console.log("List view button clicked");
      setActiveView("table");
    });
  }

  // Initialize filters
  initializeFilters();

  // Initial data load
  fetchGalleries();

  // Setup test PDF button
  const testPdfBtn = document.getElementById("test-pdf-btn");
  if (testPdfBtn) {
    testPdfBtn.addEventListener("click", () => {
      console.log("Test PDF button clicked");
      // Create test PDF content
      const content = document.createElement("div");
      content.innerHTML = `
        <h1 style="text-align: center;">Test PDF</h1>
        <p>This is a test PDF generated by the Gallery App.</p>
        <p>Current time: ${new Date().toLocaleString()}</p>
      `;

      const opt = {
        margin: 1,
        filename: "test.pdf",
        image: { type: "jpeg", quality: 0.98 },
        html2canvas: { scale: 2 },
        jsPDF: { unit: "cm", format: "a4", orientation: "portrait" },
      };

      html2pdf().set(opt).from(content).save();
    });
  }

  // Set up filter functionality
  document.getElementById("apply-filters").addEventListener("click", () => {
    fetchGalleries();
  });

  document.getElementById("reset-filters").addEventListener("click", () => {
    if (document.getElementById("gallery-filter")) {
      document.getElementById("gallery-filter").value = "";
    }
    if (document.getElementById("user-filter")) {
      document.getElementById("user-filter").value = "";
    }
    fetchGalleries();
  });

  // Close gallery detail modal when clicking the close button
  document
    .getElementById("close-gallery-detail")
    .addEventListener("click", () => {
      document.getElementById("gallery-detail-modal").style.display = "none";
    });

  // Close gallery detail modal when clicking outside the modal
  window.addEventListener("click", (event) => {
    const modal = document.getElementById("gallery-detail-modal");
    if (event.target === modal) {
      modal.style.display = "none";
    }
  });

  // Add event listeners for print buttons
  setupPrintButtons();

  // Ensure the galleries container exists
  ensureGalleriesContainer();

  // Update gallery ratings displays
  updateGalleryRatings();

  // Load comment counts for galleries
  loadCommentCounts();

  // Load galleries
  loadGalleries();

  // Update metrics after galleries are loaded
  setTimeout(updateGalleryMetrics, 1000);
});

// Function to toggle between grid and table views
function setActiveView(viewType) {
  const gridViewBtn = document.querySelector("#grid-view-btn");
  const listViewBtn = document.querySelector("#list-view-btn");
  const gridView = document.querySelector("#grid-view");
  const tableView = document.querySelector("#table-view");

  console.log("Setting active view to:", viewType);

  // If elements don't exist, try to find them by alternative selectors
  const alternativeGridView =
    document.querySelector(".galleries-grid") ||
    document.getElementById("grid-view");
  const alternativeTableView =
    document.querySelector(".galleries-table") ||
    document.getElementById("table-view");

  if (viewType === "grid") {
    // Update button states
    gridViewBtn?.classList.add("active");
    listViewBtn?.classList.remove("active");

    // Update view visibility
    if (gridView) {
      gridView.style.display = "grid";
      tableView.style.display = "none";
    } else if (alternativeGridView) {
      alternativeGridView.style.display = "grid";
      alternativeTableView.style.display = "none";
    }

    localStorage.setItem("galleryViewPreference", "grid");
  } else {
    // Update button states
    listViewBtn?.classList.add("active");
    gridViewBtn?.classList.remove("active");

    // Update view visibility
    if (tableView) {
      tableView.style.display = "table";
      gridView.style.display = "none";
    } else if (alternativeTableView) {
      alternativeTableView.style.display = "table";
      alternativeGridView.style.display = "none";
    }

    localStorage.setItem("galleryViewPreference", "table");
  }
}

// Function to initialize filter options
async function initializeFilters() {
  try {
    const API_BASE_URL = "http://localhost:5000/api";
    const token = localStorage.getItem("token");

    // Fetch all galleries for gallery filter
    const galleryResponse = await fetch(`${API_BASE_URL}/galleries`, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });

    if (galleryResponse.ok) {
      const galleryData = await galleryResponse.json();
      const galleryFilter = document.getElementById("gallery-filter");

      if (galleryData.galleries && galleryData.galleries.length > 0) {
        galleryData.galleries.forEach((gallery) => {
          const option = document.createElement("option");
          option.value = gallery.id;
          option.textContent = gallery.name;
          galleryFilter.appendChild(option);
        });
      }
    }

    // Fetch all users for user filter (admin only)
    if (localStorage.getItem("isAdmin") === "true") {
      const userResponse = await fetch(`${API_BASE_URL}/admin/users`, {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });

      if (userResponse.ok) {
        const userData = await userResponse.json();
        const userFilter = document.getElementById("user-filter");

        if (userData.users && userData.users.length > 0) {
          userData.users.forEach((user) => {
            const option = document.createElement("option");
            option.value = user.id;
            option.textContent = user.email;
            userFilter.appendChild(option);
          });
        }
      }
    }
  } catch (error) {
    console.error("Error initializing filters:", error);
  }
}

// Function to fetch all galleries from the API
async function fetchGalleries() {
  const gridView =
    document.getElementById("grid-view") ||
    document.querySelector(".galleries-grid");
  const tableBody =
    document.getElementById("table-galleries-list") ||
    document.querySelector(".table-body");

  if (!gridView || !tableBody) {
    console.error("Gallery view containers not found");
    return;
  }

  // Set loading state
  gridView.innerHTML = '<div class="loading">Loading galleries...</div>';
  tableBody.innerHTML =
    '<tr><td colspan="5" class="loading-cell">Loading galleries...</td></tr>';

  try {
    const API_BASE_URL = "http://localhost:5000/api";
    const token = localStorage.getItem("token");

    // Get filter values
    const galleryId = document.getElementById("gallery-filter")?.value || "";
    const userId = document.getElementById("user-filter")?.value || "";

    // Build query string based on filters
    let queryParams = [];
    if (galleryId) queryParams.push(`galleryId=${galleryId}`);
    if (userId) queryParams.push(`userId=${userId}`);
    const queryString =
      queryParams.length > 0 ? `?${queryParams.join("&")}` : "";

    console.log(
      `Fetching galleries from: ${API_BASE_URL}/galleries${queryString}`
    );

    const response = await fetch(`${API_BASE_URL}/galleries${queryString}`, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });

    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(errorData.error || "Failed to fetch galleries");
    }

    const data = await response.json();
    console.log("Galleries data:", data);

    // Restore the user's preferred view or use grid as default
    const preferredView =
      localStorage.getItem("galleryViewPreference") || "grid";
    setActiveView(preferredView);

    if (data.galleries && data.galleries.length > 0) {
      // Update grid view
      renderGalleries(data.galleries, gridView);

      // Update table view
      renderTableView(data.galleries, tableBody);
    } else {
      // Show empty state for both views
      gridView.innerHTML = `
        <div class="empty-galleries">
          <h3>No galleries available</h3>
          <p>Check back later for new content!</p>
        </div>
      `;
      tableBody.innerHTML = `
        <tr>
          <td colspan="5" class="empty-cell">
            No galleries available
          </td>
        </tr>
      `;
    }
  } catch (error) {
    console.error("Error fetching galleries:", error);

    // Show error state for both views
    gridView.innerHTML = `
      <div class="error-message">
        <h3>Error loading galleries</h3>
        <p>${error.message}</p>
      </div>
    `;
    tableBody.innerHTML = `
      <tr>
        <td colspan="5" class="error-cell">
          Error loading galleries: ${error.message}
        </td>
      </tr>
    `;
  }
}

// Function to render galleries in grid view
function renderGalleries(galleries, container) {
  if (!container) {
    console.error("Gallery container element not found");
    return;
  }

  container.innerHTML = "";

  if (galleries.length === 0) {
    container.innerHTML = `
      <div class="empty-galleries">
        <h3>No galleries available</h3>
        <p>Check back later for new content!</p>
      </div>
    `;
    return;
  }

  // Create gallery cards
  galleries.forEach((gallery) => {
    const card = document.createElement("div");
    card.className = "gallery-card";
    card.setAttribute("data-id", gallery.id);

    // Use a data URI for the placeholder to prevent 404 errors
    const placeholderImage =
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iI2VlZWVlZSIvPjx0ZXh0IHg9IjUwJSIgeT0iNTAlIiBmb250LWZhbWlseT0iQXJpYWwsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMjgiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGRvbWluYW50LWJhc2VsaW5lPSJtaWRkbGUiIGZpbGw9IiM5OTk5OTkiPk5vIEltYWdlPC90ZXh0Pjwvc3ZnPg==";

    // Get gallery thumbnail or use placeholder
    let thumbnailUrl = gallery.thumbnail_path;

    // Only try to load the thumbnail if it's actually available
    if (!thumbnailUrl || thumbnailUrl === "images/placeholder.jpg") {
      thumbnailUrl = placeholderImage;
    }

    card.innerHTML = `
      <div class="gallery-thumbnail">
        <img src="${thumbnailUrl}" alt="${
      gallery.name
    }" onerror="this.src='${placeholderImage}'">
      </div>
      <div class="gallery-info">
        <h3 class="gallery-name">${gallery.name}</h3>
        
        <!-- Add rating and comments count with Font Awesome icons -->
        <div class="gallery-stats">
          <span class="rating"><i class="fas fa-star"></i> ${
            gallery.average_rating || "0.0"
          }</span>
          <span class="comments-count"><i class="fas fa-comment"></i> ${
            gallery.comments_count || "0"
          }</span>
        </div>
        
        <!-- Add the print button here -->
        <button class="print-gallery-btn btn-sm" data-gallery-id="${
          gallery.id
        }" data-gallery-name="${gallery.name}">
          <i class="fas fa-print"></i> Print Details
        </button>
      </div>
    `;

    // Add click event to open gallery
    card.addEventListener("click", function (e) {
      // Only navigate if the click wasn't on the print button
      if (!e.target.closest(".print-gallery-btn")) {
        window.location.href = `gallery-detail.html?id=${gallery.id}`;
      }
    });

    container.appendChild(card);
  });

  // Set up print buttons after rendering
  setupPrintButtons();
}

// Function to render galleries in table view
function renderTableView(galleries, tableBody) {
  if (!tableBody) {
    console.error("Table body element not found");
    return;
  }

  tableBody.innerHTML = "";

  if (galleries.length === 0) {
    tableBody.innerHTML = `
      <tr>
        <td colspan="6" class="empty-cell">
          No galleries available
        </td>
      </tr>
    `;
    return;
  }

  // Create table rows for each gallery
  galleries.forEach((gallery) => {
    const row = document.createElement("tr");

    // Use a data URI for the placeholder to prevent 404 errors
    const placeholderImage =
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjUwIiBoZWlnaHQ9IjUwIiBmaWxsPSIjZWVlZWVlIi8+PHRleHQgeD0iNTAlIiB5PSI1MCUiIGZvbnQtZmFtaWx5PSJBcmlhbCwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZG9taW5hbnQtYmFzZWxpbmU9Im1pZGRsZSIgZmlsbD0iIzk5OTk5OSI+Tm8gSW1hZ2U8L3RleHQ+PC9zdmc+";

    // Get gallery thumbnail or use placeholder
    let thumbnailUrl = gallery.thumbnail_path;
    if (!thumbnailUrl || thumbnailUrl === "images/placeholder.jpg") {
      thumbnailUrl = placeholderImage;
    }

    row.innerHTML = `
      <td>
        <img src="${thumbnailUrl}" alt="${
      gallery.name
    }" class="table-thumbnail" onerror="this.src='${placeholderImage}'">
      </td>
      <td>${gallery.name}</td>
      <td><i class="fas fa-star"></i> ${gallery.average_rating || "0.0"}</td>
      <td><i class="fas fa-comment"></i> ${gallery.comments_count || "0"}</td>
      <td>
        <button class="btn-sm view-btn" data-id="${gallery.id}">View</button>
        <button class="print-gallery-btn btn-sm" data-gallery-id="${
          gallery.id
        }" data-gallery-name="${gallery.name}">
          <i class="fas fa-print"></i> Print
        </button>
      </td>
    `;

    tableBody.appendChild(row);

    // Add click event to view button
    row.querySelector(".view-btn").addEventListener("click", (e) => {
      e.stopPropagation();
      window.location.href = `gallery-detail.html?id=${gallery.id}`;
    });
  });

  // Add setupPrintButtons here too to ensure buttons are properly set up
  setTimeout(() => setupPrintButtons(), 100);
}

// Function to show gallery detail in a modal
function showGalleryDetail(gallery, avgRating, commentCount) {
  // Set gallery details in the modal
  document.getElementById("gallery-detail-title").textContent = gallery.name;
  document.getElementById("gallery-detail-description").textContent =
    gallery.description || "No description available";
  document.getElementById("gallery-detail-rating").textContent = avgRating;
  document.getElementById("gallery-detail-comments").textContent = commentCount;

  // Clear previous images
  document.getElementById("gallery-images").innerHTML =
    '<div class="loading">Loading images...</div>';

  // Show the modal
  document.getElementById("gallery-detail-modal").style.display = "block";

  // Fetch images for this gallery
  fetchGalleryImages(gallery.id);
}

// Function to fetch images for a specific gallery
async function fetchGalleryImages(galleryId) {
  const imagesContainer = document.getElementById("gallery-images");
  const token = localStorage.getItem("token");

  try {
    const API_BASE_URL = "http://localhost:5000/api";
    console.log(`Fetching images for gallery ${galleryId}`);

    const response = await fetch(
      `${API_BASE_URL}/galleries/${galleryId}/images`,
      {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      }
    );

    if (!response.ok) {
      // For testing when no real images endpoint exists yet
      console.log("Creating mock image data since endpoint returned an error");

      // Mock image data for testing
      const mockImages = [
        {
          id: 1,
          url: "https://via.placeholder.com/300x200?text=Image+1",
          title: "Image 1",
        },
        {
          id: 2,
          url: "https://via.placeholder.com/300x200?text=Image+2",
          title: "Image 2",
        },
        {
          id: 3,
          url: "https://via.placeholder.com/300x200?text=Image+3",
          title: "Image 3",
        },
        {
          id: 4,
          url: "https://via.placeholder.com/300x200?text=Image+4",
          title: "Image 4",
        },
      ];

      imagesContainer.innerHTML = "";
      mockImages.forEach((image) => {
        const imageElement = document.createElement("div");
        imageElement.className = "image-item";
        imageElement.innerHTML = `<img src="${image.url}" alt="${image.title}">`;
        imagesContainer.appendChild(imageElement);
      });

      return;
    }

    const data = await response.json();

    if (data.images && data.images.length > 0) {
      imagesContainer.innerHTML = "";

      // Display each image
      data.images.forEach((image) => {
        const imageElement = document.createElement("div");
        imageElement.className = "image-item";
        imageElement.innerHTML = `<img src="${image.url}" alt="${image.title}">`;

        // Add click event for full-size view (optional)
        imageElement.addEventListener("click", () => {
          // Show full-size image view (implement later)
          console.log("View full-size image:", image.id);
        });

        imagesContainer.appendChild(imageElement);
      });
    } else {
      imagesContainer.innerHTML = `
        <div class="empty-message">
          <p>No images in this gallery yet.</p>
        </div>
      `;
    }
  } catch (error) {
    console.error("Error fetching gallery images:", error);

    // Create mock images for testing when the API fails
    const mockImages = [
      {
        id: 1,
        url: "https://via.placeholder.com/300x200?text=Sample+1",
        title: "Sample 1",
      },
      {
        id: 2,
        url: "https://via.placeholder.com/300x200?text=Sample+2",
        title: "Sample 2",
      },
    ];

    imagesContainer.innerHTML = "";
    mockImages.forEach((image) => {
      const imageElement = document.createElement("div");
      imageElement.className = "image-item";
      imageElement.innerHTML = `<img src="${image.url}" alt="${image.title}">`;
      imagesContainer.appendChild(imageElement);
    });
  }
}

// Helper function to format dates
function formatDate(dateString) {
  const date = new Date(dateString);
  return date.toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

// Add event listeners for print buttons
function setupPrintButtons() {
  console.log("Setting up print buttons");
  setTimeout(() => {
    // Use setTimeout to ensure the DOM is fully rendered
    const buttons = document.querySelectorAll(".print-gallery-btn");
    console.log(`Found ${buttons.length} print buttons`);

    buttons.forEach((button) => {
      button.addEventListener("click", function (e) {
        console.log("Print button clicked");
        e.preventDefault();
        e.stopPropagation(); // Prevent opening the gallery when clicking the print button

        const galleryId = this.getAttribute("data-gallery-id");
        const galleryName = this.getAttribute("data-gallery-name");
        console.log(`Printing gallery: ${galleryName} (${galleryId})`);

        printGalleryDetails(galleryId);
      });
    });
  }, 100);
}

// Update print gallery function to include comments and ratings
async function printGalleryDetails(galleryId) {
  try {
    console.log("Starting to print gallery", galleryId);

    // Fetch gallery details
    const token = localStorage.getItem("token");
    if (!token) {
      window.location.href = "index.html";
      return;
    }

    const API_BASE_URL = "http://localhost:5000/api";

    // Fetch gallery data
    const galleryResponse = await fetch(
      `${API_BASE_URL}/galleries/${galleryId}`,
      {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      }
    );

    if (!galleryResponse.ok) {
      throw new Error("Failed to fetch gallery details");
    }

    const gallery = await galleryResponse.json();
    console.log("Gallery data for printing:", gallery);

    // Fetch comments
    const commentsResponse = await fetch(
      `${API_BASE_URL}/galleries/${galleryId}/comments`,
      {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      }
    );

    let comments = [];
    if (commentsResponse.ok) {
      comments = await commentsResponse.json();
      console.log("Comments for printing:", comments);
    }

    // Fetch ratings
    const ratingsResponse = await fetch(
      `${API_BASE_URL}/galleries/${galleryId}/ratings`,
      {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      }
    );

    let ratings = { averageRating: "N/A", totalRatings: 0 };
    if (ratingsResponse.ok) {
      ratings = await ratingsResponse.json();
      console.log("Ratings for printing:", ratings);
    }

    // Generate content for PDF
    const content = document.createElement("div");
    content.innerHTML = `
      <h1>${gallery.name || "Gallery Details"}</h1>
      <p>Description: ${gallery.description || "No description available"}</p>
      <div>
        <h2>Ratings</h2>
        <p>Average Rating: ${ratings.averageRating}/5 (from ${
      ratings.totalRatings
    } ratings)</p>
      </div>
      <div>
        <h2>Comments (${comments.length})</h2>
        ${
          comments.length > 0
            ? comments
                .map(
                  (c) => `
              <div style="margin-bottom: 10px; padding: 10px; border: 1px solid #ddd;">
                <p><strong>${c.user_name}</strong> - ${new Date(
                    c.created_at
                  ).toLocaleString()}</p>
                <p>${c.text}</p>
              </div>
            `
                )
                .join("")
            : "<p>No comments yet</p>"
        }
      </div>
    `;

    // Configure PDF options
    const opt = {
      margin: 1,
      filename: `gallery-${galleryId}-details.pdf`,
      image: { type: "jpeg", quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: "in", format: "letter", orientation: "portrait" },
    };

    // Generate PDF
    console.log("Starting PDF generation");
    html2pdf().set(opt).from(content).save();
    console.log("PDF generation complete");
  } catch (error) {
    console.error("Error generating PDF:", error);
    alert("Error generating PDF: " + error.message);
  }
}

// Make sure the galleries-container element exists in your HTML
// If it doesn't exist, add it to your galleries.html file:
// Add this right after the filter section in galleries.html
function ensureGalleriesContainer() {
  if (!document.getElementById("galleries-container")) {
    const main = document.querySelector("main");
    const existingContainer = document.querySelector(".galleries-grid");

    if (existingContainer) {
      // If there's already a container but with a different ID, add the ID
      existingContainer.id = "galleries-container";
    } else {
      // Create a new container
      const container = document.createElement("div");
      container.id = "galleries-container";
      container.className = "galleries-grid";
      main.appendChild(container);
    }
  }
}

// Add this function to update the gallery cards with ratings
function updateGalleryRatings() {
  console.log("Updating gallery ratings display");

  const galleryCards = document.querySelectorAll(".gallery-card");
  galleryCards.forEach(async (card) => {
    const galleryId = card.getAttribute("data-id");
    if (!galleryId) return;

    try {
      const token = localStorage.getItem("token");
      if (!token) return;

      const API_BASE_URL = "http://localhost:5000/api";

      const response = await fetch(
        `${API_BASE_URL}/galleries/${galleryId}/ratings`,
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );

      if (!response.ok) return;

      const data = await response.json();
      console.log(`Ratings for gallery ${galleryId}:`, data);

      // Update the rating display in the card
      const ratingElement = card.querySelector(".rating-value");
      if (ratingElement && data.averageRating) {
        ratingElement.textContent = data.averageRating;
      }

      // Update the star icons if you have them
      const starContainer = card.querySelector(".rating-stars");
      if (starContainer) {
        updateStarDisplay(starContainer, parseFloat(data.averageRating));
      }
    } catch (error) {
      console.error(`Error loading ratings for gallery ${galleryId}:`, error);
    }
  });
}

// Helper function to update star display
function updateStarDisplay(container, rating) {
  const stars = container.querySelectorAll(".star");
  if (!stars.length) return;

  stars.forEach((star, index) => {
    if (index < Math.floor(rating)) {
      star.classList.add("star-filled");
    } else if (index < Math.ceil(rating) && index >= Math.floor(rating)) {
      star.classList.add("star-half-filled");
    } else {
      star.classList.remove("star-filled", "star-half-filled");
    }
  });
}

// Add this function to fetch and display comment counts
async function loadCommentCounts() {
  try {
    const token = localStorage.getItem("token");
    if (!token) {
      return;
    }

    const API_BASE_URL = "http://localhost:5000/api";

    console.log("Fetching comment counts for all galleries");

    const response = await fetch(`${API_BASE_URL}/galleries/comments/count`, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });

    if (!response.ok) {
      throw new Error("Failed to load comment counts");
    }

    const counts = await response.json();
    console.log("Comment counts:", counts);

    // Update gallery cards with comment counts
    counts.forEach((item) => {
      const galleryCard = document.querySelector(
        `.gallery-card[data-id="${item.gallery_id}"]`
      );
      if (galleryCard) {
        const commentCountEl = galleryCard.querySelector(".comment-count");
        if (commentCountEl) {
          commentCountEl.textContent = item.comment_count;
        } else {
          // If element doesn't exist, add it
          const metaContainer =
            galleryCard.querySelector(".gallery-meta") ||
            galleryCard.querySelector(".card-body");
          if (metaContainer) {
            const countElement = document.createElement("div");
            countElement.className = "comment-count-container";
            countElement.innerHTML = `<i class="fa fa-comment"></i> <span class="comment-count">${item.comment_count}</span>`;
            metaContainer.appendChild(countElement);
          }
        }
      }
    });
  } catch (error) {
    console.error("Error loading comment counts:", error);
  }
}

// Update the createGalleryCard function
function createGalleryCard(gallery) {
  const template = document.querySelector(".gallery-card-template");
  const clone = template.content
    ? template.content.cloneNode(true)
    : template.cloneNode(true);
  const card = clone.querySelector(".gallery-card");

  // Set gallery ID
  card.setAttribute("data-id", gallery.id);

  // Set gallery image
  const img = card.querySelector(".gallery-thumbnail");
  if (gallery.cover_image) {
    img.src = gallery.cover_image;
  } else {
    img.src = "images/placeholder.jpg";
  }

  // Set title and description
  card.querySelector(".gallery-title").textContent = gallery.title;
  card.querySelector(".gallery-description").textContent =
    gallery.description || "No description available";

  // Set rating if available
  if (gallery.average_rating) {
    card.querySelector(".rating-value").textContent = gallery.average_rating;
    card.querySelector(".rating-count").textContent = `(${
      gallery.rating_count || 0
    })`;
  }

  // Set view gallery link
  const viewButton = card.querySelector(".view-gallery");
  viewButton.href = `gallery-detail.html?id=${gallery.id}`;

  return card;
}

// Function to update gallery metrics (ratings and comments)
async function updateGalleryMetrics() {
  try {
    console.log("Updating gallery metrics");
    console.log("Debug: Inspecting gallery card structure");
    inspectGalleryCards();

    const token = localStorage.getItem("token");
    if (!token) {
      console.error("No authentication token found");
      return;
    }

    const API_BASE_URL = "http://localhost:5000/api";

    // Fetch ratings data with proper headers
    console.log("Fetching ratings data from API");
    const ratingsResponse = await fetch(
      `${API_BASE_URL}/galleries/ratings/summary`,
      {
        method: "GET",
        headers: {
          Accept: "application/json",
          Authorization: `Bearer ${token}`,
        },
      }
    );

    if (ratingsResponse.ok) {
      const ratingsData = await ratingsResponse.json();
      console.log("Successfully loaded ratings data:", ratingsData);

      // Update each gallery card with rating information
      ratingsData.forEach((ratingInfo) => {
        const galleryId = ratingInfo.gallery_id;
        const rating = ratingInfo.average_rating || "0.0";
        const count = ratingInfo.rating_count || 0;

        console.log(
          `Processing rating for gallery #${galleryId}: ${rating} (${count} ratings)`
        );

        // Find cards for this gallery - try both in grid and table views
        const galleryCards = document.querySelectorAll(
          `.gallery-card[data-id="${galleryId}"]`
        );

        galleryCards.forEach((card) => {
          if (card) {
            // Use correct class names that match the HTML template
            const ratingElement = card.querySelector(".gallery-rating");

            if (ratingElement) {
              console.log(`Updating rating for gallery #${galleryId}`);
              ratingElement.innerHTML = `<i class="fas fa-star"></i> ${rating}`;
            } else {
              console.log(`Creating rating element for gallery #${galleryId}`);
              // If element doesn't exist, find the gallery-stats container
              const statsContainer = card.querySelector(".gallery-stats");
              if (statsContainer) {
                const ratingSpan = document.createElement("span");
                ratingSpan.className = "gallery-rating";
                ratingSpan.innerHTML = `<i class="fas fa-star"></i> ${rating}`;
                statsContainer.appendChild(ratingSpan);
              }
            }
          }
        });

        // Also update table view if present
        const tableRows = document.querySelectorAll(
          `tr[data-id="${galleryId}"]`
        );
        tableRows.forEach((row) => {
          const ratingCell = row.querySelector("td:nth-child(4)");
          if (ratingCell) {
            ratingCell.innerHTML = `<i class="fas fa-star"></i> ${rating}`;
          }
        });
      });
    } else {
      console.error("Failed to fetch ratings:", await ratingsResponse.text());
    }

    // Fetch comment counts
    console.log("Fetching comment counts from API");
    const commentsResponse = await fetch(
      `${API_BASE_URL}/galleries/comments/count`,
      {
        method: "GET",
        headers: {
          Accept: "application/json",
          Authorization: `Bearer ${token}`,
        },
      }
    );

    if (commentsResponse.ok) {
      const commentsData = await commentsResponse.json();
      console.log("Successfully loaded comments data:", commentsData);

      // Update each gallery card with comment count
      commentsData.forEach((commentInfo) => {
        const galleryId = commentInfo.gallery_id;
        const commentCount = commentInfo.comment_count || 0;

        console.log(
          `Processing comments for gallery #${galleryId}: ${commentCount} comments`
        );

        // Find cards for this gallery in both views
        const galleryCards = document.querySelectorAll(
          `.gallery-card[data-id="${galleryId}"]`
        );

        galleryCards.forEach((card) => {
          if (card) {
            // Use correct class names that match the HTML template
            const commentElement = card.querySelector(".gallery-comments");

            if (commentElement) {
              console.log(`Updating comment count for gallery #${galleryId}`);
              commentElement.innerHTML = `<i class="fas fa-comment"></i> ${commentCount}`;
            } else {
              console.log(`Creating comment element for gallery #${galleryId}`);
              // If element doesn't exist, find the gallery-stats container
              const statsContainer = card.querySelector(".gallery-stats");
              if (statsContainer) {
                const commentSpan = document.createElement("span");
                commentSpan.className = "gallery-comments";
                commentSpan.innerHTML = `<i class="fas fa-comment"></i> ${commentCount}`;
                statsContainer.appendChild(commentSpan);
              }
            }
          }
        });

        // Also update table view if present
        const tableRows = document.querySelectorAll(
          `tr[data-id="${galleryId}"]`
        );
        tableRows.forEach((row) => {
          const commentCell = row.querySelector("td:nth-child(5)");
          if (commentCell) {
            commentCell.innerHTML = `<i class="fas fa-comment"></i> ${commentCount}`;
          }
        });
      });
    } else {
      console.error("Failed to fetch comments:", await commentsResponse.text());
    }
  } catch (error) {
    console.error("Error updating gallery metrics:", error);
  }
}

// Helper function to inspect gallery card structure
function inspectGalleryCards() {
  // Find all gallery cards
  const cards = document.querySelectorAll(".gallery-card");
  console.log(`Found ${cards.length} gallery cards`);

  cards.forEach((card, index) => {
    const id = card.getAttribute("data-id");
    const title =
      card.querySelector(".gallery-title")?.textContent ||
      card.querySelector(".gallery-name")?.textContent;
    const ratingEl =
      card.querySelector(".rating") || card.querySelector(".gallery-rating");
    const commentEl =
      card.querySelector(".comments-count") ||
      card.querySelector(".gallery-comments");

    console.log(
      `Card #${index + 1}: ID=${id}, Title=${
        title || "undefined"
      }, Rating Element=${ratingEl ? "Found" : "Missing"}, Comment Element=${
        commentEl ? "Found" : "Missing"
      }`
    );

    // Output the HTML structure to debug
    if (index === 0) {
      console.log("Debug: Current HTML structure:", card.innerHTML);
    }
  });
}

// Modified loadGalleries function to call updateGalleryMetrics after loading
async function loadGalleries() {
  try {
    const token = localStorage.getItem("token");
    if (!token) {
      window.location.href = "login.html";
      return;
    }

    const galleriesContainer = document.querySelector(".galleries-container");
    if (!galleriesContainer) {
      console.error("Galleries container not found");
      return;
    }

    // Show loading state
    galleriesContainer.innerHTML =
      '<div class="loading">Loading galleries...</div>';

    // Fetch galleries from API
    const API_BASE_URL = "http://localhost:5000/api";
    const response = await fetch(`${API_BASE_URL}/galleries`, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });

    if (!response.ok) {
      throw new Error(`Failed to load galleries: ${response.status}`);
    }

    const galleries = await response.json();
    console.log("Loaded galleries:", galleries);

    if (galleries.length === 0) {
      galleriesContainer.innerHTML =
        '<div class="no-galleries">No galleries found. Create your first gallery!</div>';
      return;
    }

    // Clear container and populate with gallery cards
    galleriesContainer.innerHTML = "";

    galleries.forEach((gallery) => {
      // Create the HTML for a gallery card
      const cardHTML = `
        <div class="gallery-card" data-id="${gallery.id}">
          <div class="gallery-thumbnail-container">
            <img class="gallery-thumbnail" src="${
              gallery.cover_image || "images/placeholder.jpg"
            }" alt="${gallery.name}">
          </div>
          <div class="gallery-info">
            <h3 class="gallery-title">${gallery.name}</h3>
            <p class="gallery-description">${
              gallery.description || "No description available"
            }</p>
            <div class="gallery-metrics">
              <span class="rating-container">
                <i class="fa fa-star"></i> <span class="rating-value">0.0</span>
              </span>
              <span class="comment-container">
                <i class="fa fa-comment"></i> <span class="comment-count">0</span>
              </span>
            </div>
            <a href="gallery-detail.html?id=${
              gallery.id
            }" class="btn btn-primary print-details">
              <i class="fa fa-print"></i> Print Details
            </a>
          </div>
        </div>
      `;

      // Add card to the container
      const tempDiv = document.createElement("div");
      tempDiv.innerHTML = cardHTML;
      galleriesContainer.appendChild(tempDiv.firstElementChild);
    });

    // Now that galleries are loaded, update the metrics
    console.log("Galleries loaded, updating metrics");
    await updateGalleryMetrics();
  } catch (error) {
    console.error("Error loading galleries:", error);
    const galleriesContainer = document.querySelector(".galleries-container");
    if (galleriesContainer) {
      galleriesContainer.innerHTML = `<div class="error">Error loading galleries: ${error.message}</div>`;
    }
  }
}

// Call this function after a slight delay to see the DOM structure
function debugGalleryCardStructure() {
  setTimeout(() => {
    console.log("Debug: Inspecting gallery card structure");
    inspectGalleryCards();
    console.log(
      "Debug: Current HTML structure:",
      document.querySelector(".galleries-container")?.innerHTML
    );
  }, 2000);
}

// Initialize when DOM is ready
document.addEventListener("DOMContentLoaded", function () {
  console.log("Document loaded, initializing galleries");
  loadGalleries();
  debugGalleryCardStructure(); // Add this for debugging
});

// Setup view toggle buttons - find and use only the main buttons in the toolbar
document.addEventListener("DOMContentLoaded", function () {
  // First, find all potential grid/list view buttons
  const gridViewBtns = document.querySelectorAll(
    ".grid-view-btn, #grid-view-btn, [data-view='grid']"
  );
  const listViewBtns = document.querySelectorAll(
    ".list-view-btn, #list-view-btn, [data-view='table']"
  );

  console.log(
    `Found ${gridViewBtns.length} grid buttons and ${listViewBtns.length} list buttons`
  );

  // Keep only the first set of buttons (the ones in the toolbar)
  if (gridViewBtns.length > 0 && listViewBtns.length > 0) {
    const primaryGridBtn = gridViewBtns[0];
    const primaryListBtn = listViewBtns[0];

    // Remove event listeners from all buttons first to avoid duplicates
    gridViewBtns.forEach((btn) => {
      btn.replaceWith(btn.cloneNode(true));
    });

    listViewBtns.forEach((btn) => {
      btn.replaceWith(btn.cloneNode(true));
    });

    // Re-get the first buttons after replacement
    const newGridBtn = document.querySelector(
      ".grid-view-btn, #grid-view-btn, [data-view='grid']"
    );
    const newListBtn = document.querySelector(
      ".list-view-btn, #list-view-btn, [data-view='table']"
    );

    // Add event listeners only to the primary buttons
    newGridBtn.addEventListener("click", () => {
      console.log("Grid view button clicked");
      setActiveView("grid");
    });

    newListBtn.addEventListener("click", () => {
      console.log("List view button clicked");
      setActiveView("table");
    });

    // Optionally hide duplicate buttons (after the first one)
    for (let i = 1; i < gridViewBtns.length; i++) {
      gridViewBtns[i].style.display = "none";
    }

    for (let i = 1; i < listViewBtns.length; i++) {
      listViewBtns[i].style.display = "none";
    }

    console.log("View toggle buttons configured successfully");
  }
});

// Function to fetch and display gallery ratings
async function fetchAndDisplayGalleryRatings() {
  try {
    console.log("Fetching gallery ratings from API");

    const token = localStorage.getItem("token");
    if (!token) {
      console.error("No authentication token found");
      return;
    }

    const API_BASE_URL = "http://localhost:5000/api";

    // Implement the curl command as a fetch request
    const response = await fetch(`${API_BASE_URL}/galleries/ratings/summary`, {
      method: "GET",
      headers: {
        Accept: "application/json",
        Authorization: `Bearer ${token}`,
      },
    });

    if (!response.ok) {
      throw new Error(`API request failed with status ${response.status}`);
    }

    const ratingsData = await response.json();
    console.log("Gallery ratings data:", ratingsData);

    // Update gallery cards with ratings data
    ratingsData.forEach((gallery) => {
      const galleryId = gallery.gallery_id;
      const galleryTitle = gallery.gallery_title;
      const ratingCount = gallery.rating_count;
      const averageRating = gallery.average_rating;

      console.log(
        `Updating gallery #${galleryId} (${galleryTitle}): Rating=${averageRating}, Count=${ratingCount}`
      );

      // Find all cards for this gallery
      const cards = document.querySelectorAll(
        `.gallery-card[data-id="${galleryId}"]`
      );

      cards.forEach((card) => {
        // Update rating display - try multiple class names
        const ratingElement =
          card.querySelector(".rating") ||
          card.querySelector(".gallery-rating");

        if (ratingElement) {
          ratingElement.innerHTML = `<i class="fas fa-star"></i> ${averageRating} (${ratingCount})`;
          console.log(`Updated rating for gallery #${galleryId}`);
        } else {
          // If rating element doesn't exist, create it
          console.log(`Creating rating element for gallery #${galleryId}`);
          const statsContainer = card.querySelector(".gallery-stats");

          if (statsContainer) {
            const ratingSpan = document.createElement("span");
            ratingSpan.className = "rating";
            ratingSpan.innerHTML = `<i class="fas fa-star"></i> ${averageRating} (${ratingCount})`;
            statsContainer.appendChild(ratingSpan);
            console.log(`Created new rating element for gallery #${galleryId}`);
          }
        }
      });

      // Update table rows in list view - find by gallery ID
      const tableRows = document.querySelectorAll(
        `#table-galleries-list tr[data-id="${galleryId}"]`
      );
      if (tableRows.length === 0) {
        // Try finding rows without data-id attribute by matching gallery name
        const allTableRows = document.querySelectorAll(
          "#table-galleries-list tr"
        );
        allTableRows.forEach((row) => {
          const nameCell = row.querySelector("td:nth-child(2)");
          if (nameCell && nameCell.textContent.trim() === galleryTitle) {
            // Found a matching row by name
            console.log(
              `Found table row for gallery "${galleryTitle}" by name`
            );

            // Update rating cell (3rd column)
            const ratingCell = row.querySelector("td:nth-child(3)");
            if (ratingCell) {
              ratingCell.innerHTML = `<span class="star"><i class="fas fa-star"></i> ${averageRating} (${ratingCount})</span>`;
              console.log(
                `Updated rating cell for gallery "${galleryTitle}" in table view`
              );
            }
          }
        });
      } else {
        tableRows.forEach((row) => {
          // Update rating cell (3rd column)
          const ratingCell = row.querySelector("td:nth-child(3)");
          if (ratingCell) {
            ratingCell.innerHTML = `<span class="star"><i class="fas fa-star"></i> ${averageRating} (${ratingCount})</span>`;
            console.log(
              `Updated rating cell for gallery #${galleryId} in table view`
            );
          }
        });
      }
    });

    // Also fetch and display comment counts
    await fetchAndDisplayCommentCounts();
  } catch (error) {
    console.error("Error fetching gallery ratings:", error);
  }
}

// Function to fetch and display comment counts
async function fetchAndDisplayCommentCounts() {
  try {
    console.log("Fetching gallery comment counts");

    const token = localStorage.getItem("token");
    if (!token) return;

    const API_BASE_URL = "http://localhost:5000/api";

    const response = await fetch(`${API_BASE_URL}/galleries/comments/count`, {
      method: "GET",
      headers: {
        Accept: "application/json",
        Authorization: `Bearer ${token}`,
      },
    });

    if (!response.ok) {
      throw new Error(`API request failed with status ${response.status}`);
    }

    const commentsData = await response.json();
    console.log("Gallery comments data:", commentsData);

    // Update gallery cards with comment counts
    commentsData.forEach((comment) => {
      const galleryId = comment.gallery_id;
      const commentCount = comment.comment_count || 0;

      console.log(`Updating gallery #${galleryId}: Comments=${commentCount}`);

      // Find all cards for this gallery
      const cards = document.querySelectorAll(
        `.gallery-card[data-id="${galleryId}"]`
      );

      cards.forEach((card) => {
        // Update comment display - try multiple class names
        const commentElement =
          card.querySelector(".comments-count") ||
          card.querySelector(".gallery-comments");

        if (commentElement) {
          commentElement.innerHTML = `<i class="fas fa-comment"></i> ${commentCount}`;
          console.log(`Updated comments for gallery #${galleryId}`);
        } else {
          // If comment element doesn't exist, create it
          console.log(`Creating comment element for gallery #${galleryId}`);
          const statsContainer = card.querySelector(".gallery-stats");

          if (statsContainer) {
            const commentSpan = document.createElement("span");
            commentSpan.className = "comments-count";
            commentSpan.innerHTML = `<i class="fas fa-comment"></i> ${commentCount}`;
            statsContainer.appendChild(commentSpan);
            console.log(
              `Created new comment element for gallery #${galleryId}`
            );
          }
        }
      });

      // Update table rows in list view - find by gallery ID or name
      const tableRows = document.querySelectorAll(
        `#table-galleries-list tr[data-id="${galleryId}"]`
      );
      if (tableRows.length === 0) {
        // Try to find the row by gallery name from the API data
        const galleryInfo = commentsData.find(
          (g) => g.gallery_id === galleryId
        );
        if (galleryInfo && galleryInfo.gallery_title) {
          const allTableRows = document.querySelectorAll(
            "#table-galleries-list tr"
          );
          allTableRows.forEach((row) => {
            const nameCell = row.querySelector("td:nth-child(2)");
            if (
              nameCell &&
              nameCell.textContent.trim() === galleryInfo.gallery_title
            ) {
              // Found a matching row by name
              console.log(
                `Found table row for gallery "${galleryInfo.gallery_title}" by name`
              );

              // Update comments cell (4th column)
              const commentCell = row.querySelector("td:nth-child(4)");
              if (commentCell) {
                commentCell.innerHTML = `<span class="comment"><i class="fas fa-comment"></i> ${commentCount}</span>`;
                console.log(
                  `Updated comment cell for gallery "${galleryInfo.gallery_title}" in table view`
                );
              }
            }
          });
        }
      } else {
        tableRows.forEach((row) => {
          // Update comments cell (4th column)
          const commentCell = row.querySelector("td:nth-child(4)");
          if (commentCell) {
            commentCell.innerHTML = `<span class="comment"><i class="fas fa-comment"></i> ${commentCount}</span>`;
            console.log(
              `Updated comment cell for gallery #${galleryId} in table view`
            );
          }
        });
      }
    });
  } catch (error) {
    console.error("Error fetching comment counts:", error);
  }
}

// Update the document ready function to call our new function
document.addEventListener("DOMContentLoaded", function () {
  console.log("Document loaded, initializing galleries");
  loadGalleries();

  // Call our new function after a short delay to ensure galleries are loaded
  setTimeout(fetchAndDisplayGalleryRatings, 1000);

  // Debug gallery card structure
  setTimeout(inspectGalleryCards, 1500);
});
